-- ============================================================
-- WealthPilot database schema
-- Run this in the Supabase SQL editor (Dashboard -> SQL Editor).
-- ============================================================

-- The pgcrypto extension gives us gen_random_uuid() for primary keys
-- and for the per-user session tokens below.
create extension if not exists "pgcrypto";

-- ------------------------------------------------------------
-- users: one row per person using the app.
--
-- This is a deliberately simple, password-free auth model for the MVP.
-- Each user has:
--   * a unique username (what they type to log in), and
--   * a user_token: a random, hard-to-guess identifier that stands in for
--     a session. The token is generated by the database at signup and handed
--     to the browser, which stores it and sends it on every request. The
--     server maps a token back to this row to know who is asking.
-- Swapping in real (password / OAuth) auth later means only changing how a
-- token is issued — the rest of the app already keys off users.id.
-- ------------------------------------------------------------
create table if not exists users (
  id         uuid primary key default gen_random_uuid(),
  username   text not null unique,
  user_token uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- profiles: one row per user holding their high-level finances.
-- ------------------------------------------------------------
create table if not exists profiles (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null unique references users (id) on delete cascade,
  income      numeric(12, 2) not null default 0,   -- monthly income
  net_worth   numeric(12, 2) not null default 0,
  investments numeric(12, 2) not null default 0,
  debt        numeric(12, 2) not null default 0,
  created_at  timestamptz not null default now()
);

-- ------------------------------------------------------------
-- expenses: every transaction the user logs.
-- The user_id foreign key ties each row to exactly one owner.
-- ------------------------------------------------------------
create table if not exists expenses (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references users (id) on delete cascade,
  name       text not null,
  amount     numeric(12, 2) not null,
  category   text not null,
  date       date not null,
  created_at timestamptz not null default now()
);

-- Speeds up the common "all expenses for this user, newest first" query.
create index if not exists expenses_user_date_idx
  on expenses (user_id, date desc);

-- ------------------------------------------------------------
-- income: every incoming payment the user logs (salary, freelance, etc).
-- Mirrors the expenses table so both features stay consistent.
-- ------------------------------------------------------------
create table if not exists income (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references users (id) on delete cascade,
  source     text not null,
  amount     numeric(12, 2) not null,
  category   text not null,
  date       date not null,
  created_at timestamptz not null default now()
);

-- Speeds up the common "all income for this user, newest first" query.
create index if not exists income_user_date_idx
  on income (user_id, date desc);

-- ------------------------------------------------------------
-- financial_goals: savings targets the user is working toward.
-- ------------------------------------------------------------
create table if not exists financial_goals (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references users (id) on delete cascade,
  name           text not null,
  target_amount  numeric(12, 2) not null,
  current_amount numeric(12, 2) not null default 0,
  created_at     timestamptz not null default now()
);

create index if not exists financial_goals_user_idx
  on financial_goals (user_id);

-- ------------------------------------------------------------
-- Row Level Security note:
-- The Express API connects with the service_role key, which bypasses RLS.
-- Because all access goes through our server (never directly from the
-- browser) and every query is filtered by the token-derived user id, we
-- intentionally leave RLS off for this MVP. If the browser ever talks to
-- Supabase directly, enable RLS and add per-user policies here.
-- ------------------------------------------------------------
